#!/bin/bash

set -euo pipefail

# Setup XDG_CONFIG_HOME
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"
mkdir -p "$XDG_CONFIG_HOME"/.config/nvim

# Create symlilnks for existing configurations
ln -sf "$PWD/nvim" "XDG_CONFIG_HOME"/nvim
ln -sf "$PWD/.inputrc" "$HOME"/.inputrc
ln -sf "$PWD/.tmux.conf" "$HOME"/.tmux.conf

# Fetch and setup Zsh configuratio files from my main dotfiles repo

brew trust fluxcd/tap
wget -O $HOME/.zshrc https://raw.githubusercontent.com/pcrepeau/dotfiles/main/dot_zshrc
sudo apt-get install helm --yes

packages=(
  fd
  ripgrep
  npm
  lazygit
  fzf
  kubectl
  fluxcd/tap/flux
  derailed/k9s/k9s
  direnv
  neovim
  vim
  lsd
  bat
  kubectx
  sops
  age
  gnupg
)

# Iterate over the array and install each package
for package in "${packages[@]}"; do
  echo "Installing $package..."
  /home/linuxbrew/.linuxbrew/bin/brew install "$package"
done

echo "All packages have been installed."

if command -v zsh >/dev/null; then
  sudo chsh -s $(command -v zsh) $USER
fi

if ! command -v chezmoi >/dev/null; then
  sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply https://github.com/pcrepeau/dotfiles.git
fi

if [ ! -d "$HOME/.zsh" ]; then
  mkdir -p "$HOME/.zsh"
fi

if [ ! -d "$HOME/.zsh/pure" ]; then
  git clone https://github.com/sindresorhus/pure.git "$HOME/.zsh/pure"
fi

touch "$HOME/.privaterc"
echo 'eval "$(direnv hook zsh)"' >>~/.zshrc && source ~/.zshrc

exit 0
